exposed_registry: $local_registry
QUAY_TOKEN: "{{ lookup( 'env', 'QUAY_TOKEN') | default('') }}"
remote_app_registry: quay.io
remote_app_ns:
- name: redhat
  ns: redhat-operators
  remote_registry: registry.redhat.io
  source_registry: registry.redhat.io
- name: community
  ns: community-operators
  remote_registry: registry.redhat.io
  source_registry: registry.redhat.io
- name: certified
  ns: certified-operators
  remote_registry: registry.redhat.io
  source_registry: registry.redhat.io
- name: stage
  ns: redhat-operators-stage
  remote_registry: registry.stage.redhat.io
  source_registry: registry.stage.redhat.io
- name: dev
  ns: rh-osbs-operators
  remote_registry: image-registry.openshift-image-registry.svc:5000
  source_registry: registry-proxy.engineering.redhat.com
- name: mtc
  ns: mtcmetadata
  remote_registry: registry.stage.redhat.io
  source_registry: registry.stage.redhat.io
